database:
  host: "mongo1"
  port: "27017"
  username: "admin"
  password: "admin"
  database: "magazin"
  max_connections: 20
  min_pool_size: 10
  auth: false
  replica_set: myReplicaSet
  url: mongodb://admin:admin@localhost:27017/?replicate_set=myReplicaSet      

s3:
  region: ""
  endpoint: ""
  access_key_id: ""
  secret_access_key: ""
  image_bucket: ""

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

server:
  host: localhost
  port: ":12000"
  secret_symmetric_key: "hello-world"
  token_expiry_hours: 48
  admin_docs_users:
    - username: "admin"
      password: "admin"
    - username: "hello"
      password: "world"
