name: Deploy Scalar API Docs

on:
  push:
    branches:
      - main # Deploy whenever main is updated

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Scalar API Docs
        run: |
          mkdir public
          npx @scalar/cli build docs/swagger.yaml --output public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
