name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome to the project!**
            
            Thanks for opening your first issue 🎉  
            We appreciate your contribution and will review it as soon as possible.  
            In the meantime, please make sure to check our [contributing guidelines](CONTRIBUTING.md) and [code of conduct](CODE_OF_CONDUCT.md).  
            
            Happy coding! 🚀
          pr-message: |
            🎉 **Thank you for your first pull request!**
            
            We really appreciate your effort in contributing to this project 🙌  
            Our team will review your changes shortly.  
            Make sure your PR follows the [contributing guidelines](CONTRIBUTING.md) and passes all checks ✅.  
            
            You're awesome! ✨
